### ISSUE TITLE
Showing userprofile of other user does not work

### ISSUE THREAD

**Issue by saschathiergart** [pritstift/IBID-ST#23]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/users/16/

Django Version: 1.8.1
Python Version: 3.4.2
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'ManageIdea',
 'ManageUsers',
 'ManageConnections',
 'Home',
 'taggit',
 'taggit_selectize',
 'guardian',
 'bootstrap3',
 'widget_tweaks',
 'bootstrapform',
 'crispy_forms')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
2.                 return view_func(request, _args, *_kwargs)
   File "/Users/sush/Documents/IBID/IBID-ST/IBID/ManageUsers/views.py" in userprofile
3.       return render(request, 'ManageUsers/profile.html', {'profile_form':get_ip_instance(userprofile),'user_form':user_form, 'ideas':ideas, 'edit_profile':edit_profile})
   File "/Users/sush/Documents/IBID/IBID-ST/IBID/ManageIdea/views.py" in get_ip_instance
4.   modInstance.instance = Instance.instance

Exception Type: AttributeError at /users/16/
Exception Value: 'UserProfile' object has no attribute 'instance'

**Comment by Packebusch** [comment]
bugfixed
